name: Run Soul Script (5 Jobs)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes

jobs:
  run-soul:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        job_number: [1,2,3,4,5]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Install cpulimit
        run: |
          sudo apt update
          sudo apt install -y cpulimit

      - name: Give execute permission
        run: |
          chmod +x *

      - name: Run soul (Job ${{ matrix.job_number }})
        run: |
          echo "Starting Job #${{ matrix.job_number }}"
          cpulimit -l 50 -- ./soul 125.253.88.217 80 50 100
